### PR TITLE
Add ',' to invoke pekofy

### LINKED ISSUE #7: use a comma as an invoker for adding peko too
just to add more pekos to messages

### PR DESCRIPTION
**Pull request by valanm22**
Added ',' to invoke pekofy

### CODE REVIEW

**Comment by bemxio** [comment]
thank you for your contribution, however by adding it as an invoker, i didn't mean a prefix, just a comma added as a punctuation mark in `en_punctuation_list` inside `modules/pekofication.py`

**Comment by valanm22** [comment]
Shall I work on this?

**Comment by bemxio** [comment]
sure, if you want to! i will then merge your PR onto the main branch

**Comment by bemxio** [comment]
alright, it seems like we are good to go! thank you for your PR!

**Comment by valanm22** [comment]
Thank you for the good first issue!

**Pull request merged**
