### PR TITLE
enhancement(reactions): Added pekorat

### LINKED ISSUE #10: random pekorat picture that activates when you say "pekorat" with a few minute cooldown
requested by u/naNELSONninonu on Reddit

### PR DESCRIPTION
**Pull request by valanm22**
Added the pekorat as you suggested but couldn't figure out how to do the cooldown.

### CODE REVIEW

**Comment by bemxio** [comment]
i told you in the issue discussion that you can use a 25% chance for the pekorat!
i added it now, and it seems like everything is looking good

**Comment by bemxio** [comment]
alright, thank you for your contribution again!
i will squash the PR onto the main branch now

**Comment by valanm22** [comment]
Oh you meant it like that. I didn't quite get that when you said 1/4. Sorry for the trouble @bemxio

**Comment by bemxio** [comment]
no problem @valanm22
also you forgot about a comma on `replies.emotions.pekorat`, but it's okay, i directly commited it into the main branch and should be up soon online

**Comment by valanm22** [comment]
Thanks @bemxio

**Pull request merged**
